### ISSUE TITLE
Idea: Create a container image that runs on UDM podman container

### ISSUE THREAD

**Issue by ericyew** [xtreme22886/SmartThings_Unifi-Presence-REST#4]
Would be awesome if this could run within a UniFi UDM podman container.
I tried, but could not get it started. Got the error:
`Error: cannot exec into container that is not running: container state improper`

Reference: https://github.com/boostchicken/udm-utilities/blob/master/run-pihole/README.md

**Comment by xtreme22886** [comment]
@ericyew

My little brother recently got a UDM so I think I'm going to bug him over Thanksgiving to let me tinker with it. Hopefully I can put something together by the end of Thanksgiving. Will let you know how it goes.

**Comment by ericyew** [comment]
Awesome.. Looking forward to the update! Thanks..

**Comment by xtreme22886** [comment]
@ericyew , so I just messed with my brothers UDM. He has the UDM not the UDM Pro. Everything worked without any code changes. I'm assuming you have the UDM Pro?

**Comment by xtreme22886** [comment]
@ericyew , sorry for the long delay :). But if you download the latest Docker image, it should be working for the UDM Pro now. I haven't updated the ARM Docker image yet. Let me know how it goes.

**Comment by bcg62** [comment]
Just gave this a go and cant seem to get it to run.

```
# podman run -it --rm --net=host --name unifi-presence-rest xtreme22886/unifi-presence-rest-arm
Trying to pull docker.io/xtreme22886/unifi-presence-rest-arm...
Getting image source signatures
Copying blob 02c32a26aa25 done
Copying blob 93dc761fecef done
Copying blob 870abc97e939 done
Copying blob 73181b0fe903 done
Copying blob 0232eea7b189 done
Copying blob 760e5af4a2ec done
Copying blob 1a60c2e4c4fa done
Copying blob 0072836c03b9 done
Copying blob fcdf7e6bc7d6 done
Copying blob fe25c2d8918d done
Copying blob 24aa5ecb2ca6 done
Copying config 639eda9dfe done
Writing manifest to image destination
Storing signatures
standard_init_linux.go:207: exec user process caused "exec format error"
```

you could also publish a multi-arch container (arm/x64) under one name which might be better than xtreme22886/unifi-presence-rest and xtreme22886/unifi-presence-rest-arm.

https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/

**Comment by ericyew** [comment]
Thanks. Sorry for the late reply as I missed the last update. I'll give it
a go soon and let you know.

**Comment by xtreme22886** [comment]
Hi @ericyew and @bcg62,

Can you guys please try downloading the latest arm Docker image and give it another go? I rebuilt my Raspberry Pi and when I downloaded the original image from Docker, it did not work. So I rebuilt the image and pushed it to Docker. I still need to look into the mutli-arch builds though, thanks for that info @bcg62.

If this new image does not work for you, let me know and I'll see if I can gain access to my cousins UDM Pro for further testing.

![image](https://user-images.githubusercontent.com/3052438/104155801-caf52880-539c-11eb-8ac8-9b2a8522686c.png)

Thanks

**Comment by bcg62** [comment]
@xtreme22886 Im still not able to run it even with the new version.

```
# podman pull xtreme22886/unifi-presence-rest-arm
Trying to pull docker.io/xtreme22886/unifi-presence-rest-arm...
Getting image source signatures
Copying blob d8925d905dad done
Copying blob abd9c5a6d774 done
Copying blob d43213eb5a44 done
Copying blob 45c4527af668 done
Copying blob 22e1f8e87a65 done
Copying blob c51dcc577019 done
Copying blob e9fc080269c6 done
Copying blob 2c1ccf4854c6 done
Copying blob 6898cbd51f44 done
Copying blob 3e9400a07ccd done
Copying blob 3b83bfccb0a1 done
Copying config ebc06af2ab done
Writing manifest to image destination
Storing signatures
ebc06af2abe48a4d97ee9519b4f4b898cb5fdec8bf42310d6c33608c8fb5a295

# podman images | grep -i arm
docker.io/xtreme22886/unifi-presence-rest-arm   latest    ebc06af2abe4   2 days ago     727 MB                     false

# podman run -it --rm --net=host --name unifi-presence-rest xtreme22886/unifi-presence-rest-arm
standard_init_linux.go:207: exec user process caused "exec format error"

```

**Comment by bcg62** [comment]
where is the dockerfile/build steps for arm? maybe i can try to build it.

**Comment by bcg62** [comment]
seems to work if i build on the UDM.

```
# podman build  -t test:test .
STEP 1: FROM python:3.7
STEP 2: RUN pip install fastapi uvicorn requests apscheduler
--> Using cache 0e1360cc3a7056bf2055d06f12c8ed375f7db02a36ee5e7bcbec26e8fcea06a9
STEP 3: EXPOSE 9443
--> Using cache f59388be43d1747f1d2aa932ce4414ff347de9b01924e7ce07fd04b41a99aa96
STEP 4: COPY ./app /app
3cc94e0af0b669ae95f52e0179433b736324bf90426453a132fc7544d943b28b
STEP 5: CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "9443"]
STEP 6: COMMIT test:test
0d0a11bdbf78076d191c1e769c58a1e33564e93fde9bda8bb8af4043122f1fa7

# podman run -it --rm --net=host --name unifi-presence-rest test:test
INFO:     Started server process [1]
INFO:uvicorn.error:Started server process [1]
INFO:     Waiting for application startup.
INFO:uvicorn.error:Waiting for application startup.
INFO:     Application startup complete.
INFO:uvicorn.error:Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:9443 (Press CTRL+C to quit)
INFO:uvicorn.error:Uvicorn running on http://0.0.0.0:9443 (Press CTRL+C to quit)
```

**Comment by bcg62** [comment]
you're building for the wrong arch.

```
# podman image inspect test:test | grep Architecture
        "Architecture": "arm64",
# podman image inspect docker.io/xtreme22886/unifi-presence-rest-arm | grep Architecture
        "Architecture": "arm",
```

**Comment by bcg62** [comment]
```
# curl http://10.0.0.1:9443/unificlients
"Unable to log into the UniFi Controller"
```

Im not sure if im missing some other config?

**Comment by xtreme22886** [comment]
> you're building for the wrong arch.
> 
> 
> # podman image inspect test:test | grep Architecture
>         "Architecture": "arm64",
> # podman image inspect docker.io/xtreme22886/unifi-presence-rest-arm | grep Architecture
>         "Architecture": "arm",
> ```

Ahh arm 32 vs 64. Thanks for that info! I'll have to see how to build an image for an arch I don't have access to. I only have arm32 devices to test/build from. Let me figure out how to build for the arm64 when I don't have any hardware running that.

**Comment by xtreme22886** [comment]
> ```
> # curl http://10.0.0.1:9443/unificlients
> "Unable to log into the UniFi Controller"
> ```
> 
> Im not sure if im missing some other config?

If you are getting "Unable to log into the UniFi Controller", then there is something wrong with your UniFi credentials. If you want, show me what your config looks like: http://10.0.0.1:9443/config (make sure to mask your password).

**Comment by ericyew** [comment]
so am I correct that this doesn't currently work still unless I manually build it for arm64?

**Comment by xtreme22886** [comment]
@ericyew, yes that is correct. I haven't had the time to figure out the multi-arch builds yet. I Googled it this AM though so maybe I'll give it another shot in the next couple days.
